### ISSUE TITLE
URL issues and online dependencies

### ISSUE THREAD

**Issue by fjifdg895ngdf** [akhenakh/mbmatch#2]
Following the installation instructions, I was able to get the default 7000 port to serve the expected web page with the JS dependencies to mapbox. The page comes up blank. In Chrome, I see the following JS errors...

```js
ajax.js:25 GET http://localhost:7000/north-america.json net::ERR_CONNECTION_REFUSED
ajax.js:25 GET http://localhost:7000/osm-liberty.json net::ERR_CONNECTION_REFUSED
ajax.js:46 GET http://localhost:7000/osm-liberty.png net::ERR_CONNECTION_REFUSED
```

It should not be "localhost". mbmatch is running on a headless server and I'm connecting to it from another machine on my local network. in my case, at this moment, it should be 192.168.1.118.

I'm also concerned about the mapbox dependencies. How do you run this "offline" if you require...?

```js
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.css' rel='stylesheet' />
```

Unless you want to rely on initial web access followed by caching, these files need to be served from mbmatch, and reside on the same server as mbmatch.

**Comment by akhenakh** [comment]
Mbmatch is a project developed for my car system which is a Qt based app.

The web interface is for debug purpose only. See https://github.com/akhenakh/mocs
So it was meant to be started on localhost only and no js needed, but would work as you expect with small fixes.

Feel free to contribute though!

**Comment by fjifdg895ngdf** [comment]
I tested this again using Raspbian and Chromium, with the server and client together on the same machine. The localhost issues went away as expected, to be replaced with mapbox-gl.js issues.

But clearly your goal for mbmatch is not a web context, and to not use mapbox at all. I would just update the mbmatch docs to reflect this.
